name: Test Endpoint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        pip install requests pytest
    - name: Setup test
      run: |
        python config/__setup_test.py
    - name: Run Hitomi Downloader
      run: |
        ./hitomi_downloader_GUI.exe --no-admin
    - name: Run tests
      run: |
        pytest